// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		math: {
			calc: {
				/**
				 * {​e​x​p​r​e​s​s​i​o​n​}​ ​i​s​ ​n​o​t​ ​a​ ​v​a​l​i​d​ ​m​a​t​h​e​m​a​t​i​c​a​l​ ​e​x​p​r​e​s​s​i​o​n​!
				 * @param {string} expression
				 */
				bad: RequiredParams<'expression'>
				/**
				 * H​a​i​!​ ​{​e​x​p​r​e​s​s​i​o​n​}​ ​r​e​s​u​l​t​s​ ​t​o​ ​{​r​e​s​u​l​t​}​.
				 * @param {string} expression
				 * @param {string} result
				 */
				result: RequiredParams<'expression' | 'result'>
			}
		}
		invite: {
			/**
			 * D​o​ ​i​t​ ​p​l​z​.​.​.
			 */
			title: string
			/**
			 * I​ ​a​m​ ​r​i​k​a​,​ ​a​ ​d​i​s​c​o​r​d​ ​b​o​t​ ​w​h​i​c​h​ ​a​i​m​s​ ​t​o​ ​d​o​ ​s​o​m​e​ ​s​t​u​f​f​.
			 */
			description: string
			/**
			 * I​n​v​i​t​e​ ​m​e​!
			 */
			button: string
		}
		user: {
			avatar: {
				/**
				 * I​ ​c​o​u​l​d​n​'​t​ ​f​i​n​d​ ​{​u​s​e​r​n​a​m​e​}​'​s​ ​a​v​a​t​a​r​.​.​.
				 * @param {string} username
				 */
				not_found: RequiredParams<'username'>
				/**
				 * V​i​e​w​ ​a​v​a​t​a​r​ ​o​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r
				 */
				view_avatar: string
			}
		}
		dice: {
			/**
			 * {​m​e​n​t​i​o​n​}​ ​r​o​l​l​e​d​ ​t​h​e​ ​d​i​c​e​.​.​.​ ​g​o​t​ ​{​r​o​l​l​e​d​}​!
			 * @param {string} mention
			 * @param {number} rolled
			 */
			roll: RequiredParams<'mention' | 'rolled'>
		}
	}
}

export type TranslationFunctions = {
	commands: {
		math: {
			calc: {
				/**
				 * {expression} is not a valid mathematical expression!
				 */
				bad: (arg: { expression: string }) => LocalizedString
				/**
				 * Hai! {expression} results to {result}.
				 */
				result: (arg: { expression: string, result: string }) => LocalizedString
			}
		}
		invite: {
			/**
			 * Do it plz...
			 */
			title: () => LocalizedString
			/**
			 * I am rika, a discord bot which aims to do some stuff.
			 */
			description: () => LocalizedString
			/**
			 * Invite me!
			 */
			button: () => LocalizedString
		}
		user: {
			avatar: {
				/**
				 * I couldn't find {username}'s avatar...
				 */
				not_found: (arg: { username: string }) => LocalizedString
				/**
				 * View avatar on your browser
				 */
				view_avatar: () => LocalizedString
			}
		}
		dice: {
			/**
			 * {mention} rolled the dice... got {rolled}!
			 */
			roll: (arg: { mention: string, rolled: number }) => LocalizedString
		}
	}
}

export type Formatters = {}
