// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-BR'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	commands: {
		user: {
			avatar: {
				/**
				 * I​ ​c​o​u​l​d​n​'​t​ ​f​i​n​d​ ​{​u​s​e​r​}​'​s​ ​a​v​a​t​a​r​.​.​.
				 * @param {string} user
				 */
				not_found: RequiredParams<'user'>
				/**
				 * V​i​e​w​ ​a​v​a​t​a​r​ ​o​n​ ​y​o​u​r​ ​b​r​o​w​s​e​r
				 */
				view_avatar: string
			}
		}
		dice: {
			/**
			 * {​u​s​e​r​}​ ​r​o​l​l​e​d​ ​t​h​e​ ​d​i​c​e​.​.​.​ ​g​o​t​ ​{​r​o​l​l​e​d​}​!
			 * @param {number} rolled
			 * @param {string} user
			 */
			roll: RequiredParams<'rolled' | 'user'>
		}
	}
}

export type TranslationFunctions = {
	commands: {
		user: {
			avatar: {
				/**
				 * I couldn't find {user}'s avatar...
				 */
				not_found: (arg: { user: string }) => LocalizedString
				/**
				 * View avatar on your browser
				 */
				view_avatar: () => LocalizedString
			}
		}
		dice: {
			/**
			 * {user} rolled the dice... got {rolled}!
			 */
			roll: (arg: { rolled: number, user: string }) => LocalizedString
		}
	}
}

export type Formatters = {}
